services:

  redis:
    image: redis:7.4.0
    container_name: redis
    restart: on-failure
    expose:
      - 6379
  app:
    build: .
    container_name: flask_app
    restart: on-failure
    depends_on:
      - redis
    expose:
      - 8000
  nginx:
    build: ../web/nginx
    container_name: nginx_flask_app
    restart: on-failure
    ports:
      - "80:80"
